language: node_js
node_js:
- 10
script:
- npm install grunt-cli -g
- npm install
- grunt build --target='prod'
- printf '.gitignore\ndeployed*' > dist/.gitignore
- printf 'assets.metodiev.dev' > dist/CNAME
- cp 'README.md' dist
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: releases
  api_key:
    secure: NBl2nArLhGA/Fob4pkXIpwANJDBKoHpbYeXNYXzXxjZZa4DgXWKh9E7rDbeXFHsE78pnDfF3jfbfUgkvDqZhrgEjn93t+C0SQQn5dobfT3Kls/ttsD6vYtP/P6RYTtQQo0UEYhq4UsN3+0duP4r+qBmtZ9DzRQ1JTHn6fxbDfd/TgpxG3Qht0oBSvUAUyU/CXIaModjv1yjiyHF7hz0A9w4TE/rninLvPPhS78gMfljrR2heiaGefRM4KfStFiTdZDgDWDj/Ynhc1NuWL+3sW5YZ/yvGeB9i4LxOhBUIBEm1DDxHQW/CQyhS0uxCFrnRVLAm/7tyiXe9v273QBEODFkdm6QZptkYTMN2EdDvdV+bjSTSd3MQQNanpQSfIEDZSPJNQ5hz07y2J3ufcNRN/xSaXx/cRHu9RT97HezaIL9iCXPftFN6nRD6uXnihZQcq2E53Zf35s+5widXMxoi6Meeruhg8zIcq4vvYRCMCs/W9Dr6kZGWNTwIP19iMQbtZpTVAVhJBK7UVSOcqqvIYfmGXYUk1OxJtvtS3GQsAgw3BsU5HOz+mlHZMS3+dI5PNgO/U7Msn3AJ+yeQWLLDown2eUx8CLfGDS9bqvSwIMlbSXW2qDMsK8jkIHARjWuvEgB54v0LHxlcrRgFu0SMaXfMsX/6wilq4Rcsrd5eqHQ=
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token:
    secure: NBl2nArLhGA/Fob4pkXIpwANJDBKoHpbYeXNYXzXxjZZa4DgXWKh9E7rDbeXFHsE78pnDfF3jfbfUgkvDqZhrgEjn93t+C0SQQn5dobfT3Kls/ttsD6vYtP/P6RYTtQQo0UEYhq4UsN3+0duP4r+qBmtZ9DzRQ1JTHn6fxbDfd/TgpxG3Qht0oBSvUAUyU/CXIaModjv1yjiyHF7hz0A9w4TE/rninLvPPhS78gMfljrR2heiaGefRM4KfStFiTdZDgDWDj/Ynhc1NuWL+3sW5YZ/yvGeB9i4LxOhBUIBEm1DDxHQW/CQyhS0uxCFrnRVLAm/7tyiXe9v273QBEODFkdm6QZptkYTMN2EdDvdV+bjSTSd3MQQNanpQSfIEDZSPJNQ5hz07y2J3ufcNRN/xSaXx/cRHu9RT97HezaIL9iCXPftFN6nRD6uXnihZQcq2E53Zf35s+5widXMxoi6Meeruhg8zIcq4vvYRCMCs/W9Dr6kZGWNTwIP19iMQbtZpTVAVhJBK7UVSOcqqvIYfmGXYUk1OxJtvtS3GQsAgw3BsU5HOz+mlHZMS3+dI5PNgO/U7Msn3AJ+yeQWLLDown2eUx8CLfGDS9bqvSwIMlbSXW2qDMsK8jkIHARjWuvEgB54v0LHxlcrRgFu0SMaXfMsX/6wilq4Rcsrd5eqHQ=
  on:
    tags: true
