## DEFAULT ##

default:
  - 'dev'



## DEV ##

dev:
   description: 'Firing up the dev environment'
   tasks:
     - 'build'
     - 'watch'



## MERGE FEATURE ##

merge_feature:
  description: 'Merging a feature'
  tasks:
    - 'shell:feature'



## PREPARE RELEASE ##

prepare_release:
  description: 'Preparing for a new release'
  tasks:
    - 'shell:prepare'



## RELEASE ##

release_patch:
  description: 'Releasing a patch version'
  tasks:
    - 'bump-only:patch'
    - 'shell:release'

release_minor:
  description: 'Releasing a minor version'
  tasks:
    - 'bump-only:minor'
    - 'shell:release'

release_major:
  description: 'Releasing a major version'
  tasks:
    - 'bump-only:major'
    - 'shell:release'